//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOIKnjiznicaWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clanovi()
        {
            this.Clanovi_Auth_Protocol = new HashSet<Clanovi_Auth_Protocol>();
            this.Je_Favorit = new HashSet<Je_Favorit>();
            this.Stanje_Publikacije = new HashSet<Stanje_Publikacije>();
        }
    
        public int id { get; set; }
        public string hrEduPersonUniqueID { get; set; }
        public string mobitelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clanovi_Auth_Protocol> Clanovi_Auth_Protocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Je_Favorit> Je_Favorit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stanje_Publikacije> Stanje_Publikacije { get; set; }
    }
}
