//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOIKnjiznicaWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanovi_Auth_Protocol
    {
        public int ClanoviId { get; set; }
        public int Auth_ProtocolId { get; set; }
        public string podaci { get; set; }
        public Nullable<bool> odabrano { get; set; }
    
        public virtual Auth_Protocol Auth_Protocol { get; set; }
        public virtual Clanovi Clanovi { get; set; }
    }
}
