//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOIKnjiznicaWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Je_Favorit
    {
        public int PublikacijeId { get; set; }
        public int ClanoviId { get; set; }
        public string pomocno { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Publikacije Publikacije { get; set; }
    }
}
