//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOIKnjiznicaWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanje_Publikacije
    {
        public int id { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<System.DateTime> datum_do { get; set; }
        public int KopijaId { get; set; }
        public int Vrsta_StatusaId { get; set; }
        public int ClanoviId { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Kopija_Publikacije Kopija_Publikacije { get; set; }
        public virtual Vrsta_Statusa Vrsta_Statusa { get; set; }
    }
}
